# Generated by Django 3.2.10 on 2021-12-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='einvoice',
            old_name='generate_batch_no',
            new_name='generate_no',
        ),
        migrations.RenameField(
            model_name='einvoice',
            old_name='generate_batch_no_sha1',
            new_name='generate_no_sha1',
        ),
    ]
