# Generated by Django 3.2.7 on 2021-10-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.legalentity', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='turnkeyweb',
            unique_together={('seller', 'name')},
        ),
    ]
