# Generated by Django 3.2.8 on 2021-10-30 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einvoiceprintlog',
            name='copy_order',
        ),
        migrations.AddField(
            model_name='einvoiceprintlog',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='einvoiceprintlog',
            name='is_original_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='einvoiceprintlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
