# Generated by Django 3.2.7 on 2021-10-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taiwan_einvoice', '0002_auto_20211006_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
