# Generated by Django 3.2.7 on 2021-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0002_auto_20211021_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnectescposweblog',
            name='channel_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
