# Generated by Django 3.2.10 on 2022-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0002_add_basic_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalturnkeyweb',
            name='name',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='turnkeyweb',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
