# Generated by Django 3.2.10 on 2022-01-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0002_add_basic_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escposweb',
            options={'permissions': (('operate_te_escposweb', 'Operate ESCPOSWeb'),)},
        ),
    ]
