# Generated by Django 3.2.8 on 2021-11-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0002_auto_20211030_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoiceprintlog',
            name='user',
            field=models.ForeignKey(default=102, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
