# Generated by Django 3.2.10 on 2021-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0002_auto_20211223_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='batch_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
