# Generated by Django 3.2.10 on 2022-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0002_add_basic_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturnkeyweb',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turnkeyweb',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
    ]
