# Generated by Django 3.2.10 on 2021-12-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0003_einvoice_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoice',
            name='no',
            field=models.CharField(max_length=8),
        ),
    ]
