# Generated by Django 3.2.7 on 2021-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0003_auto_20211012_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='generate_batch_no_sha1',
            field=models.CharField(default='', max_length=10),
        ),
    ]
