# Generated by Django 3.2.10 on 2022-06-21 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0003_auto_20220115_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTurnkeyWeb',
            new_name='HistoricalTurnkeyService',
        ),
        migrations.RenameModel(
            old_name='TurnkeyWeb',
            new_name='TurnkeyService',
        ),
        migrations.AlterModelOptions(
            name='historicalturnkeyservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical turnkey service'},
        ),
        migrations.AlterModelOptions(
            name='turnkeyservice',
            options={'permissions': (('edit_te_turnkeyservicegroup', 'Edit the groups of TurnkeyService'), ('view_te_sellerinvoicetrackno', 'View Seller Invoice Track No'), ('add_te_sellerinvoicetrackno', 'Add Seller Invoice Track No'), ('delete_te_sellerinvoicetrackno', 'Delete Seller Invoice Track No'), ('view_te_einvoice', 'View E-Invoice'), ('view_te_canceleinvoice', 'View Cancel E-Invoice'), ('add_te_canceleinvoice', 'Add Cancel E-Invoice'), ('view_te_einvoiceprintlog', 'View E-Invoice Print Log'))},
        ),
    ]
