# Generated by Django 3.2.8 on 2021-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0003_alter_einvoiceprintlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoiceprintlog',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
