# Generated by Django 3.2.8 on 2021-11-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0004_einvoiceprintlog_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnkeyweb',
            options={'permissions': (('add_te_sellerinvoicetrackno', 'Add Seller Invoice Track No'), ('view_te_einvoice', 'View E-Invoice'), ('print_te_einvoice', 'Print E-Invoice'))},
        ),
    ]
