# Generated by Django 3.2.10 on 2022-06-24 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0004_auto_20220621_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnkeyservice',
            options={'permissions': (('edit_te_turnkeyservicegroup', 'Edit the groups of TurnkeyService'), ('view_te_sellerinvoicetrackno', 'View Seller Invoice Track No'), ('add_te_sellerinvoicetrackno', 'Add Seller Invoice Track No'), ('delete_te_sellerinvoicetrackno', 'Delete Seller Invoice Track No'), ('view_te_einvoice', 'View E-Invoice'), ('view_te_canceleinvoice', 'View Cancel E-Invoice'), ('add_te_canceleinvoice', 'Add Cancel E-Invoice'), ('view_te_voideinvoice', 'View Void E-Invoice'), ('add_te_voideinvoice', 'Add Void E-Invoice'), ('view_te_einvoiceprintlog', 'View E-Invoice Print Log'))},
        ),
        migrations.AddField(
            model_name='einvoice',
            name='reverse_void_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='einvoice',
            unique_together={('seller_invoice_track_no', 'track', 'no', 'reverse_void_order')},
        ),
        migrations.CreateModel(
            name='VoidEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_identifier', models.CharField(db_index=True, max_length=8)),
                ('buyer_identifier', models.CharField(db_index=True, max_length=10)),
                ('generate_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('einvoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.einvoice')),
                ('new_einvoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_einvoice_void_einvoice_set', to='taiwan_einvoice.einvoice')),
            ],
        ),
    ]
