# Generated by Django 3.2.8 on 2021-11-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0005_alter_turnkeyweb_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerinvoicetrackno',
            unique_together={('type', 'begin_time', 'end_time', 'track', 'begin_no', 'end_no')},
        ),
    ]
