# Generated by Django 3.2.10 on 2022-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0005_auto_20220624_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceleinvoice',
            name='ei_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='ei_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voideinvoice',
            name='ei_synced',
            field=models.BooleanField(default=False),
        ),
    ]
