# Generated by Django 3.2.8 on 2021-11-11 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0006_alter_sellerinvoicetrackno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnkeyweb',
            name='epl_base_set',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='HistoricalTurnkeyWeb',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('on_working', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('hash_key', models.CharField(max_length=40)),
                ('transport_id', models.CharField(max_length=10)),
                ('party_id', models.CharField(max_length=10)),
                ('routing_id', models.CharField(max_length=39)),
                ('qrcode_seed', models.CharField(max_length=40)),
                ('turnkey_seed', models.CharField(max_length=40)),
                ('download_seed', models.CharField(max_length=40)),
                ('epl_base_set', models.CharField(default='', max_length=64)),
                ('note', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='taiwan_einvoice.seller')),
            ],
            options={
                'verbose_name': 'historical turnkey web',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
