# Generated by Django 3.2.10 on 2022-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0007_auto_20220628_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoice',
            name='carrier_type',
            field=models.CharField(choices=[('3J0002', 'Mobile barcode'), ('CQ0001', 'Natural person barcode')], db_index=True, default='', max_length=6),
        ),
    ]
