# Generated by Django 3.2.8 on 2021-11-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0007_auto_20211111_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceSellerAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppId', models.CharField(max_length=18, unique=True)),
                ('APIKey', models.CharField(max_length=24)),
                ('proxy', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EInvoiceAPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'mobile-barcode'), ('2', 'donate-mark'), ('3', 'seller-enable-einvoice'), ('4', 'seller-identifier'), ('5', 'seller-customer-carrier')], max_length=1)),
                ('key', models.CharField(max_length=40)),
                ('success', models.BooleanField(default=False)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('type', 'key')},
            },
        ),
    ]
