# Generated by Django 3.2.8 on 2021-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0008_einvoiceapiresult_einvoicesellerapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoiceapiresult',
            name='type',
            field=models.CharField(choices=[('1', 'mobile-barcode'), ('2', 'donate-mark'), ('3', 'seller-enable-einvoice'), ('4', 'seller-identifier')], max_length=1),
        ),
    ]
