# Generated by Django 3.2.8 on 2021-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0009_alter_einvoiceapiresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoice',
            name='carrier_id1',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='carrier_id2',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='carrier_type',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
    ]
