# Generated by Django 3.2.10 on 2022-07-02 09:37

from django.db import migrations, models
import django.db.models.deletion
from django.utils.translation import gettext_lazy as _


no_choices = (
    ('A0101', _('B2B Exchange Invoice')),
    ('A0102', _('B2B Exchange Invoice Confirm')),
    ('B0101', _('B2B Exchange Allowance')),
    ('B0102', _('B2B Exchange Allowance Confirm')),
    ('A0201', _('B2B Exchange Cancel Invoice')),
    ('A0202', _('B2B Exchange Cancel Invoice Confirm')),
    ('B0201', _('B2B Exchange Cancel Allowance')),
    ('B0202', _('B2B Exchange Cancel Allowance Confirm')),
    ('A0301', _('B2B Exchange Reject Invoice')),
    ('A0302', _('B2B Exchange Reject Invoice Confirm')),

    ('A0401', _('B2B Certificate Invoice')),
    ('B0401', _('B2B Certificate Allowance')),
    ('A0501', _('B2B Certificate Cancel Invoice')),
    ('B0501', _('B2B Certificate Cancel Allowance')),
    ('A0601', _('B2B Certificate Reject Invoice')),

    ('C0401', _('B2C Certificate Invoice')),
    ('C0501', _('B2C Certificate Cancel Invoice')),
    ('C0701', _('B2C Certificate Void Invoice')),
    ('D0401', _('B2C Certificate Allowance')),
    ('D0501', _('B2C Certificate Cancel Allowance')),

    ('E0401', _('Branch Track')),
    ('E0402', _('Branch Track Blank')),
    ('E0501', _('Invoice Assign No')),
)


def create_default_mig(apps, schema_editor):
    EInvoiceMIG = apps.get_model('taiwan_einvoice', 'EInvoiceMIG')
    for emig in no_choices:
        e = EInvoiceMIG(no=emig[0])
        e.save()
    

def delete_default_mig(apps, schema_editor):
    EInvoiceMIG = apps.get_model('taiwan_einvoice', 'EInvoiceMIG')
    for emig in no_choices:
        e = EInvoiceMIG.objects.get(no=emig[0])
        e.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0009_alter_voideinvoice_new_einvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceMIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(choices=[('A0101', 'B2B Exchange Invoice'), ('A0102', 'B2B Exchange Invoice Confirm'), ('B0101', 'B2B Exchange Allowance'), ('B0102', 'B2B Exchange Allowance Confirm'), ('A0201', 'B2B Exchange Cancel Invoice'), ('A0202', 'B2B Exchange Cancel Invoice Confirm'), ('B0201', 'B2B Exchange Cancel Allowance'), ('B0202', 'B2B Exchange Cancel Allowance Confirm'), ('A0301', 'B2B Exchange Reject Invoice'), ('A0302', 'B2B Exchange Reject Invoice Confirm'), ('A0401', 'B2B Certificate Invoice'), ('B0401', 'B2B Certificate Allowance'), ('A0501', 'B2B Certificate Cancel Invoice'), ('B0501', 'B2B Certificate Cancel Allowance'), ('A0601', 'B2B Certificate Reject Invoice'), ('C0401', 'B2C Certificate Invoice'), ('C0501', 'B2C Certificate Cancel Invoice'), ('C0701', 'B2C Certificate Void Invoice'), ('D0401', 'B2C Certificate Allowance'), ('D0501', 'B2C Certificate Cancel Allowance'), ('E0401', 'Branch Track'), ('E0402', 'Branch Track Blank'), ('E0501', 'Invoice Assign No')], max_length=5, unique=True)),
            ],
        ),
        migrations.RunPython(create_default_mig, delete_default_mig),
    ]