# Generated by Django 3.2.8 on 2021-11-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0011_alter_einvoice_carrier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturnkeyweb',
            name='forbidden_above_amount',
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='historicalturnkeyweb',
            name='warning_above_amount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='turnkeyweb',
            name='forbidden_above_amount',
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='turnkeyweb',
            name='warning_above_amount',
            field=models.IntegerField(default=10000),
        ),
    ]
