# Generated by Django 3.2.10 on 2022-07-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('taiwan_einvoice', '0011_auto_20220702_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.CharField(max_length=14, unique=True)),
                ('kind', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('0', 'Collecting'), ('1', 'Waiting for trigger(Stop Collecting)'), ('2', 'Uploading to TKW'), ('3', 'Uploaded to TKW'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('m', 'Swith to Successful EI process manually(S-C)')], db_index=True, default='0', max_length=1)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('mig_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.einvoicemig')),
                ('turnkey_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.turnkeyservice')),
            ],
        ),
        migrations.CreateModel(
            name='BatchEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('body_json', models.TextField()),
                ('result_code', models.CharField(db_index=True, default='', max_length=5)),
                ('pass_if_error', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.uploadbatch')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
        ),
    ]
