# Generated by Django 3.2.8 on 2021-11-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0012_auto_20211125_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnkeyweb',
            options={'permissions': (('add_te_sellerinvoicetrackno', 'Add Seller Invoice Track No'), ('view_te_einvoice', 'View E-Invoice'), ('print_te_einvoice', 'Print E-Invoice'), ('cancel_te_einvoice', 'Cancel E-Invoice'))},
        ),
        migrations.RenameField(
            model_name='canceleinvoice',
            old_name='cancel_time',
            new_name='generate_time',
        ),
        migrations.RemoveField(
            model_name='canceleinvoice',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='canceleinvoice',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='canceleinvoice',
            name='new_einvoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_einvoice_cancel_einvoice_set', to='taiwan_einvoice.einvoice'),
        ),
    ]
