# Generated by Django 3.2.10 on 2022-07-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0012_batcheinvoice_uploadbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='auto_upload_c0401_einvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='tkw_endpoint',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='upload_cronjob_format',
            field=models.CharField(choices=[('*/5 * * * *', 'per 5 minutes'), ('*/10 * * * *', 'per 10 minutes'), ('*/15 * * * *', 'per 15 minutes'), ('*/20 * * * *', 'per 20 minutes'), ('*/30 * * * *', 'per 30 minutes'), ('*/60 * * * *', 'per 60 minutes')], db_index=True, default='*/15 * * * *', max_length=128),
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='auto_upload_c0401_einvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='tkw_endpoint',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='upload_cronjob_format',
            field=models.CharField(choices=[('*/5 * * * *', 'per 5 minutes'), ('*/10 * * * *', 'per 10 minutes'), ('*/15 * * * *', 'per 15 minutes'), ('*/20 * * * *', 'per 20 minutes'), ('*/30 * * * *', 'per 30 minutes'), ('*/60 * * * *', 'per 60 minutes')], db_index=True, default='*/15 * * * *', max_length=128),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('0', 'Collecting'), ('1', 'Waiting for trigger(Stop Collecting)'), ('2', 'Noticed to TKW'), ('3', 'Uploading to TKW'), ('4', 'Uploaded to TKW'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('m', 'Swith to Successful EI process manually(S-C)')], db_index=True, default='0', max_length=1),
        ),
    ]
