# Generated by Django 3.2.10 on 2022-07-15 23:01

from django.db import migrations


INITIAL_CRON_FUNCTION = ['taiwan_einvoice.crontabs.polling_upload_batch', ]

def forward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    for value in INITIAL_CRON_FUNCTION:
        cf_so = SelectOption(swarm='cron-function', value=value)
        cf_so.save()

    insp = Inspection(
        cron_format='*/5 * * * *',
        name="polling_upload_batch",
        function_option=cf_so,
        function_note="Polling UploadBatch"
    )
    insp.save()


def backward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    insp = Inspection.objects.filter(name="polling_upload_batch",
                                     function_option__value__in=INITIAL_CRON_FUNCTION)
    insp.delete()

    cf_sos = SelectOption.objects.filter(swarm='cron-function', value__in=INITIAL_CRON_FUNCTION)
    cf_sos.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('crontab_monitor', '0004_auto_20220328_1408'),
        ('taiwan_einvoice', '0013_auto_20220705_0336'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
