# Generated by Django 3.2.8 on 2021-11-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0013_auto_20211125_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelEInvoice',
        ),
    ]
