# Generated by Django 3.2.10 on 2022-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0014_add_polling_upload_batch_crontab_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batcheinvoice',
            name='body_json',
        ),
        migrations.AddField(
            model_name='batcheinvoice',
            name='body',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalturnkeyservice',
            name='upload_cronjob_format',
            field=models.CharField(choices=[('*/5 * * * *', 'once per 5 minutes'), ('*/10 * * * *', 'once per 10 minutes'), ('*/15 * * * *', 'once per 15 minutes'), ('*/20 * * * *', 'once per 20 minutes'), ('*/30 * * * *', 'once per 30 minutes'), ('*/60 * * * *', 'once per 60 minutes')], db_index=True, default='*/15 * * * *', max_length=128),
        ),
        migrations.AlterField(
            model_name='turnkeyservice',
            name='upload_cronjob_format',
            field=models.CharField(choices=[('*/5 * * * *', 'once per 5 minutes'), ('*/10 * * * *', 'once per 10 minutes'), ('*/15 * * * *', 'once per 15 minutes'), ('*/20 * * * *', 'once per 20 minutes'), ('*/30 * * * *', 'once per 30 minutes'), ('*/60 * * * *', 'once per 60 minutes')], db_index=True, default='*/15 * * * *', max_length=128),
        ),
    ]
