# Generated by Django 3.2.8 on 2021-11-25 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0014_delete_canceleinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_identifier', models.CharField(db_index=True, max_length=8)),
                ('buyer_identifier', models.CharField(db_index=True, max_length=10)),
                ('generate_time', models.DateTimeField()),
                ('readon', models.CharField(max_length=20)),
                ('return_tax_document_number', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('einvoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.einvoice')),
                ('new_einvoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_einvoice_cancel_einvoice_set', to='taiwan_einvoice.einvoice')),
            ],
        ),
    ]
