# Generated by Django 3.2.10 on 2022-07-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


NAME_CHOICES = (
    ("TEA_CEC_PROCESSING", "TEA/CEC Processing"),
    ("UPLOAD_TO_EITURNKEY", "Upload to EITurnkey"),
    ("EITURNKEY_PROCESSING", "EITurnkey Processing"),
    ("EI_PROCESSING", "EI Processing"),
)


def add_audittype(apps, schema_editor):
    AuditType = apps.get_model('taiwan_einvoice', 'AuditType')
    for nc in NAME_CHOICES:
        adt = AuditType(name=nc[0])
        adt.save()



def remove_audittype(apps, schema_editor):
    AuditType = apps.get_model('taiwan_einvoice', 'AuditType')
    for nc in NAME_CHOICES:
        adt = AuditType.objects.get(name=nc[0])
        adt.delete()



def add_taiwan_einvoice_sys_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    sys_user = User(username="^taiwan_einvoice_sys_user$",
                    first_name="Sys",
                    last_name="Taiwan E-Invoice",
                    email="taiwaneinvoicesysuser@ho600.com.taiwanei",
                    is_active=False,
                    is_staff=False,
                    is_superuser=False)
    sys_user.save()



def remove_taiwan_einvoice_sys_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    sys_user = User.objects.get(username="^taiwan_einvoice_sys_user$")
    sys_user.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0015_auto_20220718_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TEA_CEC_PROCESSING', 'TEA/CEC Processing'), ('UPLOAD_TO_EITURNKEY', 'Upload to EITurnkey'), ('EITURNKEY_PROCESSING', 'EITurnkey Processing'), ('EI_PROCESSING', 'EI Processing')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('log', models.JSONField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('turnkey_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.turnkeyservice')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taiwan_einvoice.audittype')),
                ('is_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            add_audittype, remove_audittype
        ),
        migrations.RunPython(
            add_taiwan_einvoice_sys_user, remove_taiwan_einvoice_sys_user
        )
    ]
