# Generated by Django 3.2.8 on 2021-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0015_canceleinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceleinvoice',
            old_name='readon',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='canceleinvoice',
            name='remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='canceleinvoice',
            name='return_tax_document_number',
            field=models.CharField(default='', max_length=60),
        ),
    ]
