# Generated by Django 3.2.8 on 2021-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0017_auto_20211126_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceleinvoice',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='canceleinvoice',
            name='return_tax_document_number',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
