# Generated by Django 3.2.10 on 2022-07-21 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0017_alter_uploadbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batcheinvoice',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 1, 22, 3, 611433, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batcheinvoice',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 1, 22, 9, 479634, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batcheinvoice',
            name='track_no',
            field=models.CharField(default='NO24634102', max_length=10),
            preserve_default=False,
        ),
    ]
