# Generated by Django 3.2.10 on 2022-07-21 01:29
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


def update_batch_einvoices(apps, schema_editor):
    BatchEInvoice = apps.get_model('taiwan_einvoice', 'BatchEInvoice')
    EInvoice = apps.get_model('taiwan_einvoice', 'EInvoice')

    for bei in BatchEInvoice.objects.all().order_by('id'):
        if 'einvoice' == bei.content_type.model:
            ei = EInvoice.objects.get(id=bei.object_id)
            bei.begin_time = ei.seller_invoice_track_no.begin_time
            bei.end_time = ei.seller_invoice_track_no.end_time
            bei.track_no = "{}{}".format(ei.track, ei.no)
            bei.save()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0018_auto_20220721_0122'),
    ]

    operations = [
        migrations.RunPython(update_batch_einvoices, lambda x, y: '/dev/null'),
    ]
