# Generated by Django 3.2.10 on 2022-07-29 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0021_auto_20220722_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceleinvoice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='einvoice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voideinvoice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='kind',
            field=models.CharField(choices=[('wp', 'Wait for printed'), ('cp', 'Could print'), ('np', 'No need to print'), ('57', 'Wait for C0501 or C0701'), ('w4', 'Wait for C0401'), ('54', 'Wait for C0501 or C0401')], max_length=2),
        ),
    ]
