# Generated by Django 3.2.10 on 2022-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0023_auto_20220730_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryreport',
            old_name='is_resolve',
            new_name='is_resolved',
        ),
        migrations.RenameField(
            model_name='summaryreport',
            old_name='resolve_note',
            new_name='resolved_note',
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='problems',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='resolved_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='resolved_counts',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='resolved_objects',
            field=models.ManyToManyField(related_name='summary_report_set_as_resolved_object', to='taiwan_einvoice.EInvoicesContentType'),
        ),
        migrations.AlterField(
            model_name='einvoicescontenttype',
            name='status',
            field=models.CharField(choices=[('', 'Waiting'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('-', 'BatchEInvoice does exist')], db_index=True, default='', max_length=1),
        ),
    ]
