# Generated by Django 3.2.10 on 2022-08-04 02:14
from django.db import migrations, models


NAME_CHOICES = (
    ("EI_SUMMARY_RESULT", "EI Summary Result"),
)


def add_audittype(apps, schema_editor):
    AuditType = apps.get_model('taiwan_einvoice', 'AuditType')
    for nc in NAME_CHOICES:
        adt = AuditType(name=nc[0])
        adt.save()



def remove_audittype(apps, schema_editor):
    AuditType = apps.get_model('taiwan_einvoice', 'AuditType')
    for nc in NAME_CHOICES:
        adt = AuditType.objects.get(name=nc[0])
        adt.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0026_add_polling_turnkey_service_to_get_ei_turnkey_daily_summary_result'),
    ]

    operations = [
        migrations.RunPython(
            add_audittype, remove_audittype
        ),
    ]
