# Generated by Django 3.2.10 on 2022-08-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0027_increase_auditlog_audittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittype',
            name='name',
            field=models.CharField(choices=[('TEA_CEC_PROCESSING', 'TEA/CEC Processing'), ('UPLOAD_TO_EITURNKEY', 'Upload to EITurnkey'), ('EITURNKEY_PROCESSING', 'EITurnkey Processing'), ('EI_PROCESSING', 'EI Processing'), ('EI_PROCESSED', 'EI Processed'), ('EI_SUMMARY_RESULT', 'EI Summary Result')], max_length=32, unique=True),
        ),
    ]
