# Generated by Django 3.2.10 on 2022-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0030_auto_20220804_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreport',
            name='report_type',
            field=models.CharField(choices=[('h', 'Hourly Sync'), ('d', 'Daily Sync'), ('w', 'Weekly Sync'), ('m', 'Monthly Sync'), ('o', 'Odd month ~ Even month Sync'), ('y', 'Yearly Sync'), ('a', 'Daily Audit'), ('E', 'Daily Summary from EI')], db_index=True, max_length=1),
        ),
    ]
