# Generated by Django 3.2.10 on 2022-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0032_auto_20220806_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinvoicetrackno',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
