# Generated by Django 3.2.10 on 2022-08-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0033_sellerinvoicetrackno_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='batcheinvoice',
            name='result_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalbatcheinvoice',
            name='result_message',
            field=models.TextField(default=''),
        ),
    ]
