# Generated by Django 3.2.10 on 2022-08-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0034_auto_20220809_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnkeyservice',
            options={'permissions': (('edit_te_turnkeyservicegroup', 'Edit the groups of the TurnkeyService'), ('view_te_sellerinvoicetrackno', 'View Seller Invoice Track No of the TurnkeyService'), ('add_te_sellerinvoicetrackno', 'Add Seller Invoice Track No of the TurnkeyService'), ('delete_te_sellerinvoicetrackno', 'Delete Seller Invoice Track No of the TurnkeyService'), ('view_te_einvoice', 'View E-Invoice of the TurnkeyService'), ('view_te_canceleinvoice', 'View Cancel E-Invoice of the TurnkeyService'), ('add_te_canceleinvoice', 'Add Cancel E-Invoice of the TurnkeyService'), ('view_te_voideinvoice', 'View Void E-Invoice of the TurnkeyService'), ('add_te_voideinvoice', 'Add Void E-Invoice of the TurnkeyService'), ('handle_te_batcheinvoice', 'Handle Batch E-Invoice of the TurnkeyService'), ('view_te_einvoiceprintlog', 'View E-Invoice Print Log of the TurnkeyService'), ('view_te_summaryreport', 'View Summary Report of the TurnkeyService'), ('resolve_te_summaryreport', 'Resolve Summary Report of the TurnkeyService'), ('view_te_alarm_for_general_user', 'View Alarm for the General User of the TurnkeyService'), ('view_te_alarm_for_programmer', 'View Alarm for the Programmer of the TurnkeyService'))},
        ),
    ]
