# Generated by Django 3.2.10 on 2022-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0035_alter_turnkeyservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='batcheinvoice',
            name='handling_note',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalbatcheinvoice',
            name='handling_note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
