# Generated by Django 3.2.10 on 2022-08-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0038_add_GENERAL_CONSUMER_IDENTIFIER'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinvoicetrackno',
            old_name='turnkey_web',
            new_name='turnkey_service',
        ),
    ]
