# Generated by Django 3.2.10 on 2022-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0039_rename_turnkey_web_sellerinvoicetrackno_turnkey_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='verify_tkw_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='verify_tkw_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
