# Generated by Django 3.2.16 on 2022-10-10 17:16
from django.db import migrations


INITIAL_CRON_FUNCTION = ['taiwan_einvoice.crontabs.auto_generate_summary_report', ]

def forward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    for value in INITIAL_CRON_FUNCTION:
        cf_so = SelectOption(swarm='cron-function', value=value)
        cf_so.save()

    insp = Inspection(
        cron_format='27 * * * *',
        name="auto_generate_summary_report",
        function_option=cf_so,
        function_note="Auto-generating Summary Report"
    )
    insp.save()


def backward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    insp = Inspection.objects.filter(name="auto_generate_summary_report",
                                     function_option__value__in=INITIAL_CRON_FUNCTION)
    insp.delete()

    cf_sos = SelectOption.objects.filter(swarm='cron-function', value__in=INITIAL_CRON_FUNCTION)
    cf_sos.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0040_auto_20220829_0712'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
