# Generated by Django 3.2.16 on 2022-10-18 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taiwan_einvoice', '0041_add_auto_generate_summary_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffProfile',
            new_name='TEAStaffProfile',
        ),
    ]
