# Generated by Django 3.2.16 on 2022-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0042_rename_staffprofile_teastaffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinvoicetrackno',
            name='allow_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
