# Generated by Django 3.2.16 on 2023-03-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0043_sellerinvoicetrackno_allow_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='receipt_type',
            field=models.CharField(choices=[('5', '58mm Receipt'), ('6', '58mm E-Invoice'), ('7', '58mm E-Invoice in 80mm Machine'), ('8', '80mm Receipt')], max_length=1),
        ),
    ]
