# Generated by Django 4.2.4 on 2023-08-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0046_add_polling_turnkey_service_to_get_ei_turnkey_e0501_invoice_assign_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='e0501invoiceassignno',
            name='booklet',
            field=models.SmallIntegerField(default=0),
        ),
    ]
