# Generated by Django 4.2.4 on 2023-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0047_e0501invoiceassignno_booklet'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='member_vehicle_id',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalturnkeyservice',
            name='member_vehicle_key',
            field=models.CharField(default='********************************', max_length=32),
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='member_vehicle_id',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='turnkeyservice',
            name='member_vehicle_key',
            field=models.CharField(default='********************************', max_length=32),
        ),
    ]
