# Generated by Django 4.2.4 on 2023-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0047_e0501invoiceassignno_booklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batcheinvoice',
            name='status',
            field=models.CharField(choices=[('', 'Waiting'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('.', 'Failed but pass(.)')], db_index=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='einvoicescontenttype',
            name='status',
            field=models.CharField(choices=[('', 'Waiting'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('.', 'Failed but pass(.)'), ('-', 'BatchEInvoice does exist')], db_index=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalbatcheinvoice',
            name='status',
            field=models.CharField(choices=[('', 'Waiting'), ('p', 'Preparing for EI(P)'), ('g', 'Uploaded to EI or Downloaded from EI(G)'), ('e', 'E Error for EI process(E)'), ('i', 'I Error for EI process(I)'), ('c', 'Successful EI process(C)'), ('.', 'Failed but pass(.)')], db_index=True, default='', max_length=1),
        ),
    ]
