# Generated by Django 4.2.7 on 2023-11-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0048_historicalturnkeyservice_member_vehicle_id_and_more'),
        ('taiwan_einvoice', '0049_alter_legalentity_name'),
    ]

    operations = [
    ]
