# Generated by Django 4.2.4 on 2024-02-21 01:41

from django.db import migrations


NAMES = [
    {"group_name": 'TaiwanEInvoicePrinterAdminGroup',
        "permissions": [
            "taiwan_einvoice.view_escposweb",
            "taiwan_einvoice.edit_te_escposweboperator",
            "taiwan_einvoice.view_staffprofile",
        ]},
    {"group_name": 'TaiwanEInvoiceManagerGroup',
        "permissions": [
            "taiwan_einvoice.view_staffprofile",
            "taiwan_einvoice.add_staffprofile",
            "taiwan_einvoice.change_staffprofile",
            "taiwan_einvoice.edit_te_turnkeywebgroup",
        ]},
]


def rename_codename(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    for group_permissions in NAMES:
        group = Group.objects.get(name=group_permissions['group_name'])
        pcodes = [p for p in group_permissions['permissions'] if '_staffprofile' in p]
        for pcode in pcodes:
            app, code = pcode.split('.')
            p = Permission.objects.get(codename=code)
            group.permissions.remove(p)
            np = Permission.objects.get(codename=code.replace('_staffprofile', '_teastaffprofile'))
            group.permissions.add(np)



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0049_alter_legalentity_name'),
    ]

    operations = [
        migrations.RunPython(rename_codename, lambda x, y: '/dev/null'),
    ]
