# Generated by Django 4.2.13 on 2024-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0050_rename_staffprofile_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoicemig',
            name='no',
            field=models.CharField(choices=[('A0101', 'B2B Exchange Invoice'), ('A0102', 'B2B Exchange Invoice Confirm'), ('B0101', 'B2B Exchange Allowance'), ('B0102', 'B2B Exchange Allowance Confirm'), ('A0201', 'B2B Exchange Cancel Invoice'), ('A0202', 'B2B Exchange Cancel Invoice Confirm'), ('B0201', 'B2B Exchange Cancel Allowance'), ('B0202', 'B2B Exchange Cancel Allowance Confirm'), ('A0301', 'B2B Exchange Reject Invoice'), ('A0302', 'B2B Exchange Reject Invoice Confirm'), ('A0401', 'B2B Certificate Invoice'), ('B0401', 'B2B Certificate Allowance'), ('A0501', 'B2B Certificate Cancel Invoice'), ('B0501', 'B2B Certificate Cancel Allowance'), ('A0601', 'B2B Certificate Reject Invoice'), ('C0401', 'B2C Certificate Invoice'), ('C0501', 'B2C Certificate Cancel Invoice'), ('C0701', 'B2C Certificate Void Invoice'), ('D0401', 'B2C Certificate Allowance'), ('D0501', 'B2C Certificate Cancel Allowance'), ('E0401', 'Branch Track'), ('E0402', 'Branch Track Blank'), ('E0501', 'Invoice Assign No'), ('F0401', 'B2B/B2C Certificate Invoice'), ('F0501', 'B2B/B2C Certificate Cancel Invoice'), ('F0701', 'B2B/B2C Certificate Void Invoice')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaluploadbatch',
            name='kind',
            field=models.CharField(choices=[('wp', 'Wait for printed'), ('cp', 'Could print'), ('np', 'No need to print'), ('57', 'Wait for F0501 or F0701'), ('w4', 'Wait for F0401'), ('54', 'Wait for F0501 or F0401'), ('E', 'E0401 ~ E0501'), ('R', 'Re-Created by error status'), ('RN', 'Re-Created by error status with the new track no.')], max_length=2),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='kind',
            field=models.CharField(choices=[('wp', 'Wait for printed'), ('cp', 'Could print'), ('np', 'No need to print'), ('57', 'Wait for F0501 or F0701'), ('w4', 'Wait for F0401'), ('54', 'Wait for F0501 or F0401'), ('E', 'E0401 ~ E0501'), ('R', 'Re-Created by error status'), ('RN', 'Re-Created by error status with the new track no.')], max_length=2),
        ),
    ]
