# Generated by Django 4.2.4 on 2024-02-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0050_merge_20231116_0556'),
        ('taiwan_einvoice', '0050_rename_staffprofile_codename'),
    ]

    operations = [
    ]
