# Generated by Django 4.2.13 on 2024-11-29 07:47

from django.db import migrations
from django.utils.translation import gettext_lazy as _


no_choices = (
    ('F0401', _('B2B/B2C Certificate Invoice')),
    ('F0501', _('B2B/B2C Certificate Cancel Invoice')),
    ('F0701', _('B2B/B2C Certificate Void Invoice')),
)


def create_default_mig(apps, schema_editor):
    EInvoiceMIG = apps.get_model('taiwan_einvoice', 'EInvoiceMIG')
    for emig in no_choices:
        e = EInvoiceMIG(no=emig[0])
        e.save()
    

def delete_default_mig(apps, schema_editor):
    EInvoiceMIG = apps.get_model('taiwan_einvoice', 'EInvoiceMIG')
    for emig in no_choices:
        e = EInvoiceMIG.objects.get(no=emig[0])
        e.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0051_alter_einvoicemig_no_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_mig, delete_default_mig),
    ]