# Generated by Django 4.2.13 on 2024-11-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0051_merge_20240221_0208'),
        ('taiwan_einvoice', '0052_add_F0401_F0501_F0701'),
    ]

    operations = [
    ]
