# Generated by Django 4.2.13 on 2024-12-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0053_alter_historicaluploadbatch_status_and_more'),
        ('taiwan_einvoice', '0053_merge_20241129_1000'),
    ]

    operations = [
    ]
