# Generated by Django 4.2.13 on 2025-03-22 06:45

from django.db import migrations


INITIAL_CRON_FUNCTION = ['taiwan_einvoice.crontabs.warn_managers_from_the_blank_track_number_is_below_the_threshold', ]

def forward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    for value in INITIAL_CRON_FUNCTION:
        cf_so = SelectOption(swarm='cron-function', value=value)
        cf_so.save()

    insp = Inspection(
        cron_format='#45 17 * * *',
        name="warn_managers_from_the_blank_track_number_is_below_the_threshold",
        function_option=cf_so,
        function_note="Warn managers from the blank track number is below the threshold"
    )
    insp.save()


def backward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    insp = Inspection.objects.filter(name="warn_managers_from_the_blank_track_number_is_below_the_threshold",
                                     function_option__value__in=INITIAL_CRON_FUNCTION)
    insp.delete()

    cf_sos = SelectOption.objects.filter(swarm='cron-function', value__in=INITIAL_CRON_FUNCTION)
    cf_sos.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0053_alter_historicaluploadbatch_status_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
