# Generated by Django 4.2.13 on 2025-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0054_add_inspection_warn_managers_from_the_blank_track_number_is_below_the_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoice',
            name='carrier_id1',
            field=models.CharField(db_index=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='carrier_id2',
            field=models.CharField(db_index=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='npoban',
            field=models.CharField(db_index=True, default='', max_length=10),
        ),
    ]
