# Generated by Django 4.2.13 on 2025-03-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0054_add_inspection_warn_managers_from_the_blank_track_number_is_below_the_threshold'),
        ('taiwan_einvoice', '0054_merge_20241202_0220'),
    ]

    operations = [
    ]
