# Generated by Django 4.2.13 on 2025-05-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taiwan_einvoice', '0055_alter_einvoice_carrier_id1_and_more'),
        ('taiwan_einvoice', '0055_merge_20250322_0724'),
    ]

    operations = [
    ]
