# Generated by Django 3.2.5 on 2021-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptlog',
            name='original_width',
            field=models.CharField(choices=[('5', '58mm'), ('8', '80mm')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='receiptlog',
            name='print_time',
            field=models.DateTimeField(),
        ),
    ]
