# Generated by Django 3.2.7 on 2021-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptlog',
            name='re_print_original_copy',
            field=models.BooleanField(default=False),
        ),
    ]
