# Generated by Django 3.2.9 on 2021-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0002_receiptlog_re_print_original_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='default_encoding',
            field=models.CharField(choices=[('B', 'CP950'), ('G', 'GB18030')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='printer',
            name='profile',
            field=models.CharField(choices=[('-1', 'default'), ('00', 'TM-T88IV'), ('01', 'TM-T88V')], max_length=2),
        ),
        migrations.AlterField(
            model_name='printer',
            name='receipt_type',
            field=models.CharField(choices=[('0', 'DOES NOT WORK'), ('5', '58mm Receipt'), ('6', '58mm E-Invoice'), ('8', '80mm Receipt')], default='0', max_length=1),
        ),
    ]
