# Generated by Django 3.2.9 on 2021-11-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0003_auto_20211122_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptlog',
            name='print_mark',
            field=models.BooleanField(default=False),
        ),
    ]
