# Generated by Django 3.2.5 on 2022-06-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0004_receiptlog_print_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TEWeb',
            new_name='TEAWeb',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='te_web',
            new_name='tea_web',
        ),
    ]
