# Generated by Django 3.2.13 on 2022-09-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0005_auto_20220622_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaweb',
            name='slug',
            field=models.CharField(max_length=5),
        ),
    ]
