# Generated by Django 3.2.13 on 2022-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0007_alter_teaweb_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaweb',
            name='name',
            field=models.CharField(default='name', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teaweb',
            name='now_use',
            field=models.BooleanField(default=False),
        ),
    ]
