# Generated by Django 3.2.13 on 2022-09-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0008_auto_20220902_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaweb',
            name='now_use',
            field=models.BooleanField(default=True),
        ),
    ]
