# Generated by Django 3.2.13 on 2022-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0009_alter_teaweb_now_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='random_number',
            field=models.CharField(default='', max_length=4),
        ),
    ]
