# Generated by Django 3.2.13 on 2022-09-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0010_receipt_random_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('meet_to_tw_einvoice_standard', 'track_no', 'random_number')},
        ),
    ]
