# Generated by Django 3.2.13 on 2023-05-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escpos_printer', '0011_alter_receipt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='profile',
            field=models.CharField(choices=[('-1', 'POS-5890'), ('00', 'TM-T88IV'), ('01', 'TM-T88V'), ('02', 'POS-5890'), ('03', 'XP-Q90EC'), ('04', 'TP805L'), ('05', 'TM-T82III')], max_length=2),
        ),
        migrations.AlterField(
            model_name='printer',
            name='receipt_type',
            field=models.CharField(choices=[('0', 'DOES NOT WORK'), ('5', '58mm Receipt'), ('6', '58mm E-Invoice'), ('7', '58mm E-Invoice in 80mm Machine'), ('8', '80mm Receipt')], default='0', max_length=1),
        ),
    ]
