#/etc/logrotate.d/

/home/pi/django-taiwan-einvoice/escpos_web-logs/escpos_web.asgi.log {
	daily
	copytruncate
	rotate 30
	compress
	delaycompress
	notifempty
	nomail
}

/home/pi/django-taiwan-einvoice/escpos_web/logs/check_printer_status.log {
	daily
	copytruncate
	rotate 30
	compress
	delaycompress
	notifempty
	nomail
}

/home/pi/django-taiwan-einvoice/escpos_web/logs/lcd_control.log {
	daily
	copytruncate
	rotate 30
	compress
	delaycompress
	notifempty
	nomail
}
/home/pi/django-taiwan-einvoice/escpos_web/logs/print_receipt.log {
	daily
	copytruncate
	rotate 30
	compress
	delaycompress
	notifempty
	nomail
}
