# Generated by Django 3.2.14 on 2022-07-11 06:16

import os
from pathlib import Path
from django.db import migrations, models

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


class Migration(migrations.Migration):

    initial = True
    initial_sql = open(os.path.join(BASE_DIR, 'initial.sql'), 'r').read()

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(initial_sql),
        migrations.CreateModel(
            name='FROM_CONFIG',
            fields=[
                ('TRANSPORT_ID', models.CharField(blank=True, db_column='TRANSPORT_ID', max_length=10, null=True)),
                ('TRANSPORT_PASSWORD', models.CharField(blank=True, db_column='TRANSPORT_PASSWORD', max_length=45, null=True)),
                ('PARTY_ID', models.CharField(db_column='PARTY_ID', max_length=10, primary_key=True, serialize=False)),
                ('PARTY_DESCRIPTION', models.CharField(blank=True, db_column='PARTY_DESCRIPTION', max_length=200, null=True)),
                ('ROUTING_ID', models.CharField(blank=True, db_column='ROUTING_ID', max_length=39, null=True)),
                ('ROUTING_DESCRIPTION', models.CharField(blank=True, db_column='ROUTING_DESCRIPTION', max_length=200, null=True)),
                ('SIGN_ID', models.CharField(blank=True, db_column='SIGN_ID', max_length=4, null=True)),
                ('SUBSTITUTE_PARTY_ID', models.CharField(blank=True, db_column='SUBSTITUTE_PARTY_ID', db_index=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'FROM_CONFIG',
                'verbose_name_plural': 'FROM_CONFIG',
                'db_table': 'FROM_CONFIG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCHEDULE_CONFIG',
            fields=[
                ('TASK', models.CharField(db_column='TASK', max_length=30, primary_key=True, serialize=False)),
                ('ENABLE', models.CharField(blank=True, db_column='ENABLE', max_length=1, null=True)),
                ('SCHEDULE_TYPE', models.CharField(blank=True, db_column='SCHEDULE_TYPE', max_length=10, null=True)),
                ('SCHEDULE_WEEK', models.CharField(blank=True, db_column='SCHEDULE_WEEK', max_length=15, null=True)),
                ('SCHEDULE_TIME', models.CharField(blank=True, db_column='SCHEDULE_TIME', max_length=50, null=True)),
                ('SCHEDULE_PERIOD', models.CharField(blank=True, db_column='SCHEDULE_PERIOD', max_length=10, null=True)),
                ('SCHEDULE_RANGE', models.CharField(blank=True, db_column='SCHEDULE_RANGE', max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'SCHEDULE_CONFIG',
                'verbose_name_plural': 'SCHEDULE_CONFIG',
                'db_table': 'SCHEDULE_CONFIG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SIGN_CONFIG',
            fields=[
                ('SIGN_ID', models.CharField(db_column='SIGN_ID', max_length=4, primary_key=True, serialize=False)),
                ('SIGN_TYPE', models.CharField(blank=True, db_column='SIGN_TYPE', max_length=10, null=True)),
                ('PFX_PATH', models.CharField(blank=True, db_column='PFX_PATH', max_length=100, null=True)),
                ('SIGN_PASSWORD', models.CharField(blank=True, db_column='SIGN_PASSWORD', max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'SIGN_CONFIG',
                'verbose_name_plural': 'SIGN_CONFIG',
                'db_table': 'SIGN_CONFIG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TASK_CONFIG',
            fields=[
                ('CATEGORY_TYPE_CATEGORY_TYPE_TASK', models.CharField(db_column='CATEGORY_TYPE_CATEGORY_TYPE_TASK', max_length=47, primary_key=True, serialize=False)),
                ('CATEGORY_TYPE', models.CharField(db_column='CATEGORY_TYPE', max_length=5)),
                ('PROCESS_TYPE', models.CharField(db_column='PROCESS_TYPE', max_length=10)),
                ('TASK', models.CharField(db_column='TASK', max_length=30)),
                ('SRC_PATH', models.CharField(blank=True, db_column='SRC_PATH', max_length=200, null=True)),
                ('TARGET_PATH', models.CharField(blank=True, db_column='TARGET_PATH', max_length=200, null=True)),
                ('FILE_FORMAT', models.CharField(blank=True, db_column='FILE_FORMAT', max_length=20, null=True)),
                ('VERSION', models.CharField(blank=True, db_column='VERSION', max_length=5, null=True)),
                ('ENCODING', models.CharField(blank=True, db_column='ENCODING', max_length=15, null=True)),
                ('TRANS_CHINESE_DATE', models.CharField(blank=True, db_column='TRANS_CHINESE_DATE', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'TASK_CONFIG',
                'verbose_name_plural': 'TASK_CONFIG',
                'db_table': 'TASK_CONFIG_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TO_CONFIG',
            fields=[
                ('FROM_PARTY_ID_PARTY_ID', models.CharField(db_column='FROM_PARTY_ID_PARTY_ID', max_length=21, primary_key=True, serialize=False)),
                ('PARTY_ID', models.CharField(db_column='PARTY_ID', max_length=10)),
                ('PARTY_DESCRIPTION', models.CharField(blank=True, db_column='PARTY_DESCRIPTION', max_length=200, null=True)),
                ('ROUTING_ID', models.CharField(blank=True, db_column='ROUTING_ID', max_length=39, null=True)),
                ('ROUTING_DESCRIPTION', models.CharField(blank=True, db_column='ROUTING_DESCRIPTION', max_length=200, null=True)),
                ('FROM_PARTY_ID', models.CharField(db_column='FROM_PARTY_ID', max_length=10)),
            ],
            options={
                'verbose_name': 'TO_CONFIG',
                'verbose_name_plural': 'TO_CONFIG',
                'db_table': 'TO_CONFIG_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_MESSAGE_LOG',
            fields=[
                ('SEQNO_SUBSEQNO', models.CharField(db_column='SEQNO_SUBSEQNO', max_length=14, primary_key=True, serialize=False)),
                ('SEQNO', models.CharField(db_column='SEQNO', max_length=8)),
                ('SUBSEQNO', models.CharField(db_column='SUBSEQNO', max_length=5)),
                ('UUID', models.CharField(blank=True, db_column='UUID', db_index=True, max_length=40, null=True)),
                ('MESSAGE_TYPE', models.CharField(blank=True, db_column='MESSAGE_TYPE', max_length=10, null=True)),
                ('CATEGORY_TYPE', models.CharField(blank=True, db_column='CATEGORY_TYPE', max_length=5, null=True)),
                ('PROCESS_TYPE', models.CharField(blank=True, db_column='PROCESS_TYPE', max_length=10, null=True)),
                ('FROM_PARTY_ID', models.CharField(blank=True, db_column='FROM_PARTY_ID', max_length=10, null=True)),
                ('TO_PARTY_ID', models.CharField(blank=True, db_column='TO_PARTY_ID', max_length=10, null=True)),
                ('MESSAGE_DTS', models.CharField(blank=True, db_column='MESSAGE_DTS', db_index=True, max_length=17, null=True)),
                ('CHARACTER_COUNT', models.CharField(blank=True, db_column='CHARACTER_COUNT', max_length=10, null=True)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', max_length=5, null=True)),
                ('IN_OUT_BOUND', models.CharField(blank=True, db_column='IN_OUT_BOUND', max_length=1, null=True)),
                ('FROM_ROUTING_ID', models.CharField(blank=True, db_column='FROM_ROUTING_ID', max_length=39, null=True)),
                ('TO_ROUTING_ID', models.CharField(blank=True, db_column='TO_ROUTING_ID', max_length=39, null=True)),
                ('INVOICE_IDENTIFIER', models.CharField(blank=True, db_column='INVOICE_IDENTIFIER', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'TURNKEY_MESSAGE_LOG',
                'verbose_name_plural': 'TURNKEY_MESSAGE_LOG',
                'db_table': 'TURNKEY_MESSAGE_LOG_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_MESSAGE_LOG_DETAIL',
            fields=[
                ('SEQNO_SUBSEQNO_TASK', models.CharField(db_column='SEQNO_SUBSEQNO_TASK', max_length=45, primary_key=True, serialize=False)),
                ('SEQNO', models.CharField(db_column='SEQNO', max_length=8)),
                ('SUBSEQNO', models.CharField(db_column='SUBSEQNO', max_length=5)),
                ('PROCESS_DTS', models.CharField(blank=True, db_column='PROCESS_DTS', max_length=17, null=True)),
                ('TASK', models.CharField(db_column='TASK', max_length=30)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', max_length=5, null=True)),
                ('FILENAME', models.CharField(blank=True, db_column='FILENAME', db_index=True, max_length=255, null=True)),
                ('UUID', models.CharField(blank=True, db_column='UUID', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'TURNKEY_MESSAGE_LOG_DETAIL',
                'verbose_name_plural': 'TURNKEY_MESSAGE_LOG_DETAIL',
                'db_table': 'TURNKEY_MESSAGE_LOG_DETAIL_V',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_SEQUENCE',
            fields=[
                ('SEQUENCE', models.CharField(db_column='SEQUENCE', max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'TURNKEY_SEQUENCE',
                'verbose_name_plural': 'TURNKEY_SEQUENCE',
                'db_table': 'TURNKEY_SEQUENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_SYSEVENT_LOG',
            fields=[
                ('EVENTDTS', models.CharField(db_column='EVENTDTS', max_length=17, primary_key=True, serialize=False)),
                ('PARTY_ID', models.CharField(blank=True, db_column='PARTY_ID', max_length=10, null=True)),
                ('SEQNO', models.CharField(blank=True, db_column='SEQNO', max_length=8, null=True)),
                ('SUBSEQNO', models.CharField(blank=True, db_column='SUBSEQNO', max_length=5, null=True)),
                ('ERRORCODE', models.CharField(blank=True, db_column='ERRORCODE', max_length=4, null=True)),
                ('UUID', models.CharField(blank=True, db_column='UUID', db_index=True, max_length=40, null=True)),
                ('INFORMATION1', models.CharField(blank=True, db_column='INFORMATION1', max_length=100, null=True)),
                ('INFORMATION2', models.CharField(blank=True, db_column='INFORMATION2', max_length=100, null=True)),
                ('INFORMATION3', models.CharField(blank=True, db_column='INFORMATION3', max_length=100, null=True)),
                ('MESSAGE1', models.CharField(blank=True, db_column='MESSAGE1', max_length=100, null=True)),
                ('MESSAGE2', models.CharField(blank=True, db_column='MESSAGE2', max_length=100, null=True)),
                ('MESSAGE3', models.CharField(blank=True, db_column='MESSAGE3', max_length=100, null=True)),
                ('MESSAGE4', models.CharField(blank=True, db_column='MESSAGE4', max_length=100, null=True)),
                ('MESSAGE5', models.CharField(blank=True, db_column='MESSAGE5', max_length=100, null=True)),
                ('MESSAGE6', models.CharField(blank=True, db_column='MESSAGE6', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'TURNKEY_SYSEVENT_LOG',
                'verbose_name_plural': 'TURNKEY_SYSEVENT_LOG',
                'db_table': 'TURNKEY_SYSEVENT_LOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_TRANSPORT_CONFIG',
            fields=[
                ('TRANSPORT_ID', models.CharField(db_column='TRANSPORT_ID', max_length=10, primary_key=True, serialize=False)),
                ('TRANSPORT_PASSWORD', models.CharField(db_column='TRANSPORT_PASSWORD', max_length=60)),
            ],
            options={
                'verbose_name': 'TURNKEY_TRANSPORT_CONFIG',
                'verbose_name_plural': 'TURNKEY_TRANSPORT_CONFIG',
                'db_table': 'TURNKEY_TRANSPORT_CONFIG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TURNKEY_USER_PROFILE',
            fields=[
                ('USER_ID', models.CharField(db_column='USER_ID', max_length=10, primary_key=True, serialize=False)),
                ('USER_PASSWORD', models.CharField(blank=True, db_column='USER_PASSWORD', max_length=100, null=True)),
                ('USER_ROLE', models.CharField(blank=True, db_column='USER_ROLE', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'TURNKEY_USER_PROFILE',
                'verbose_name_plural': 'TURNKEY_USER_PROFILE',
                'db_table': 'TURNKEY_USER_PROFILE',
                'managed': False,
            },
        ),
    ]