# Generated by Django 3.2.14 on 2022-07-11 06:16

import os
from pathlib import Path
from django.db import migrations, models

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


class Migration(migrations.Migration):

    initial = True
    initial_sql = open(os.path.join(BASE_DIR, 'initial.sql'), 'r').read()

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(initial_sql)
    ]