# Generated by Django 3.2.14 on 2022-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0003_eiturnkey_eiturnkeybatch_eiturnkeybatcheinvoice_from_config_schedule_config_sign_config_task_config_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiturnkeybatch',
            name='slug',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterUniqueTogether(
            name='eiturnkeybatch',
            unique_together={('ei_turnkey', 'slug')},
        ),
    ]
