# Generated by Django 3.2.14 on 2022-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0004_auto_20220718_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eiturnkeybatcheinvoice',
            old_name='batch',
            new_name='ei_turnkey_batch',
        ),
        migrations.AddField(
            model_name='eiturnkeybatcheinvoice',
            name='batch_einvoice_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eiturnkeybatcheinvoice',
            name='body',
            field=models.JSONField(default=''),
        ),
    ]
