# Generated by Django 3.2.14 on 2022-07-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0006_auto_20220721_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eiturnkeybatcheinvoice',
            old_name='batch_einvoic_begin_time',
            new_name='batch_einvoice_begin_time',
        ),
        migrations.RenameField(
            model_name='eiturnkeybatcheinvoice',
            old_name='batch_einvoic_end_time',
            new_name='batch_einvoice_end_time',
        ),
        migrations.RenameField(
            model_name='eiturnkeybatcheinvoice',
            old_name='batch_einvoic_track_no',
            new_name='batch_einvoice_track_no',
        ),
    ]
