# Generated by Django 3.2.14 on 2022-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0007_auto_20220721_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eiturnkey',
            name='execute_abspath',
        ),
        migrations.AddField(
            model_name='eiturnkey',
            name='tmpdata_abspath',
            field=models.CharField(default='/tmp', max_length=755),
            preserve_default=False,
        ),
    ]
