# Generated by Django 3.2.14 on 2022-07-22 03:43
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0009_alter_eiturnkeybatch_turnkey_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eiturnkeybatcheinvoice',
            name='pass_if_error',
        ),
        migrations.AddField(
            model_name='eiturnkeybatcheinvoice',
            name='status',
            field=models.CharField(choices=[('', 'Waiting'), ('P', 'Preparing for EI(P)'), ('G', 'Uploaded to EI or Downloaded from EI(G)'), ('E', 'E Error for EI process(E)'), ('I', 'I Error for EI process(I)'), ('C', 'Successful EI process(C)')], db_index=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='eiturnkeybatch',
            name='status',
            field=models.CharField(choices=[('7', 'Just created'), ('8', 'Downloaded from TEA'), ('9', 'Exported to Data/'), ('F', 'Finish')], db_index=True, default='7', max_length=1),
        ),
        migrations.AlterField(
            model_name='eiturnkeybatch',
            name='turnkey_version',
            field=models.CharField(choices=[('3.2', 'v32')], default='3.2', max_length=8),
        ),
        migrations.AddField(
            model_name='eiturnkeybatcheinvoice',
            name='save_body_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 9, 0)),
            preserve_default=False,
        ),
    ]
