# Generated by Django 3.2.14 on 2022-07-29 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0011_add_polling_ei_turnkey_batch_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiturnkeybatcheinvoice',
            name='upload_to_ei_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
