# Generated by Django 3.2.14 on 2022-08-02 13:26

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0014_eiturnkey_can_sync_to_ei'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiturnkeybatcheinvoice',
            name='invoice_identifier',
            field=models.CharField(db_index=True, default='none', max_length=23),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eiturnkey',
            unique_together={('party_id', 'routing_id')},
        ),
    ]
