# Generated by Django 3.2.14 on 2022-08-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0016_auto_20220802_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='EITurnkeyDailySummaryResultXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('abspath', models.CharField(max_length=255, unique=True)),
                ('result_date', models.DateField()),
                ('is_parsed', models.BooleanField(default=False)),
                ('total_count', models.SmallIntegerField(default=0)),
                ('good_count', models.SmallIntegerField(default=0)),
                ('failed_count', models.SmallIntegerField(default=0)),
                ('total_batch_einvoice_ids', models.JSONField(default=[])),
                ('good_batch_einvoice_ids', models.JSONField(default=[])),
                ('failed_batch_einvoice_ids', models.JSONField(default=[])),
                ('binary_content', models.BinaryField()),
                ('ei_turnkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turnkey_wrapper.eiturnkey')),
            ],
        ),
        migrations.CreateModel(
            name='EITurnkeyDailySummaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result_date', models.DateField()),
                ('ei_turnkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turnkey_wrapper.eiturnkey')),
                ('xml_files', models.ManyToManyField(to='turnkey_wrapper.EITurnkeyDailySummaryResultXML')),
            ],
            options={
                'unique_together': {('ei_turnkey', 'result_date')},
            },
        ),
    ]
