# Generated by Django 3.2.14 on 2022-08-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0017_eiturnkeydailysummaryresult_eiturnkeydailysummaryresultxml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='failed_batch_einvoice_ids',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='failed_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='good_batch_einvoice_ids',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='good_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='total_batch_einvoice_ids',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresult',
            name='total_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='eiturnkeydailysummaryresult',
            unique_together={('ei_turnkey', 'result_date')},
        ),
    ]
