# Generated by Django 3.2.14 on 2022-08-03 08:30
from django.db import migrations


INITIAL_CRON_FUNCTION = ['turnkey_wrapper.crontabs.polling_ei_turnkey', ]

def forward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    for value in INITIAL_CRON_FUNCTION:
        cf_so = SelectOption(swarm='cron-function', value=value)
        cf_so.save()

    insp = Inspection(
        cron_format='10,40 0-4,17-23 * * *',
        name="polling_ei_turnkey",
        function_option=cf_so,
        function_note="Polling EITurnkey"
    )
    insp.save()


def backward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    insp = Inspection.objects.filter(name="polling_ei_turnkey",
                                     function_option__value__in=INITIAL_CRON_FUNCTION)
    insp.delete()

    cf_sos = SelectOption.objects.filter(swarm='cron-function', value__in=INITIAL_CRON_FUNCTION)
    cf_sos.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0017_eiturnkeydailysummaryresult_eiturnkeydailysummaryresultxml'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
