# Generated by Django 3.2.14 on 2022-08-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0018_add_polling_ei_turnkey_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiturnkeydailysummaryresultxml',
            name='error_note',
            field=models.TextField(default=''),
        ),
    ]
