# Generated by Django 3.2.14 on 2022-08-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0019_eiturnkeydailysummaryresultxml_error_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresultxml',
            name='ei_turnkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turnkey_wrapper.eiturnkey'),
        ),
        migrations.AlterField(
            model_name='eiturnkeydailysummaryresultxml',
            name='result_date',
            field=models.DateField(null=True),
        ),
    ]
