# Generated by Django 3.2.19 on 2023-07-01 04:54

import os
from pathlib import Path
from django.db import migrations

BASE_DIR = Path(__file__).resolve().parent

class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0022_create_other_views'),
    ]

    operations = [
        migrations.RunSQL(open(os.path.join(BASE_DIR,
                                            'turnkey-3.0.2.sql'),
                                            'r').read()),
    ]
