# Generated by Django 4.2.4 on 2023-08-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0022_create_other_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EITurnkeyE0501XML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('abspath', models.CharField(max_length=255, unique=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('invoice_assign_nos', models.JSONField(default=[])),
                ('binary_content', models.BinaryField()),
                ('error_note', models.TextField(default='')),
                ('ei_turnkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='turnkey_wrapper.eiturnkey')),
            ],
        ),
        migrations.CreateModel(
            name='EITurnkeyE0501InvoiceAssignNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice_type', models.CharField(choices=[('07', 'General'), ('08', 'Special')], db_index=True, default='07', max_length=2)),
                ('year_month', models.CharField(db_index=True, max_length=5)),
                ('invoice_track', models.CharField(db_index=True, max_length=2)),
                ('invoice_begin_no', models.CharField(db_index=True, max_length=8)),
                ('invoice_end_no', models.CharField(db_index=True, max_length=8)),
                ('invoice_booklet', models.SmallIntegerField(default=0)),
                ('ei_turnkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turnkey_wrapper.eiturnkey')),
                ('xml_files', models.ManyToManyField(to='turnkey_wrapper.eiturnkeydailysummaryresultxml')),
            ],
            options={
                'unique_together': {('ei_turnkey', 'invoice_type', 'year_month', 'invoice_track', 'invoice_begin_no', 'invoice_end_no', 'invoice_booklet')},
            },
        ),
    ]
