# Generated by Django 4.2.4 on 2023-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0023_eiturnkeye0501xml_eiturnkeye0501invoiceassignno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiturnkeye0501invoiceassignno',
            name='xml_files',
            field=models.ManyToManyField(to='turnkey_wrapper.eiturnkeye0501xml'),
        ),
    ]
