# Generated by Django 4.2.20 on 2025-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnkey_wrapper', '0026_alter_eiturnkeybatch_mig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiturnkeybatch',
            name='turnkey_version',
            field=models.CharField(choices=[('3.2', 'v32'), ('4.0', 'v40'), ('4.1', 'v41')], default='4.1', max_length=8),
        ),
    ]
