-- from Turnkey-2.0.2/DBSchema/MySQL/MySQL.sql

CREATE TABLE `FROM_CONFIG` (
  `TRANSPORT_ID` varchar(10) DEFAULT NULL,
  `TRANSPORT_PASSWORD` varchar(45) DEFAULT NULL,
  `PARTY_ID` varchar(10) NOT NULL,
  `PARTY_DESCRIPTION` varchar(200) DEFAULT NULL,
  `ROUTING_ID` varchar(39) DEFAULT NULL,
  `ROUTING_DESCRIPTION` varchar(200) DEFAULT NULL,
  `SIGN_ID` varchar(4) DEFAULT NULL,
  `SUBSTITUTE_PARTY_ID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`PARTY_ID`),
  KEY `FROM_CONFIG_INDEX1` (`SUBSTITUTE_PARTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `SCHEDULE_CONFIG` (
  `TASK` varchar(30) NOT NULL,
  `ENABLE` varchar(1) DEFAULT NULL,
  `SCHEDULE_TYPE` varchar(10) DEFAULT NULL,
  `SCHEDULE_WEEK` varchar(15) DEFAULT NULL,
  `SCHEDULE_TIME` varchar(50) DEFAULT NULL,
  `SCHEDULE_PERIOD` varchar(10) DEFAULT NULL,
  `SCHEDULE_RANGE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`TASK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `SIGN_CONFIG` (
  `SIGN_ID` varchar(4) NOT NULL,
  `SIGN_TYPE` varchar(10) DEFAULT NULL,
  `PFX_PATH` varchar(100) DEFAULT NULL,
  `SIGN_PASSWORD` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`SIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TASK_CONFIG` (
  `CATEGORY_TYPE` varchar(5) NOT NULL,
  `PROCESS_TYPE` varchar(10) NOT NULL,
  `TASK` varchar(30) NOT NULL,
  `SRC_PATH` varchar(200) DEFAULT NULL,
  `TARGET_PATH` varchar(200) DEFAULT NULL,
  `FILE_FORMAT` varchar(20) DEFAULT NULL,
  `VERSION` varchar(5) DEFAULT NULL,
  `ENCODING` varchar(15) DEFAULT NULL,
  `TRANS_CHINESE_DATE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`CATEGORY_TYPE`,`PROCESS_TYPE`,`TASK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TO_CONFIG` (
  `PARTY_ID` varchar(10) NOT NULL,
  `PARTY_DESCRIPTION` varchar(200) DEFAULT NULL,
  `ROUTING_ID` varchar(39) DEFAULT NULL,
  `ROUTING_DESCRIPTION` varchar(200) DEFAULT NULL,
  `FROM_PARTY_ID` varchar(10) NOT NULL,
  PRIMARY KEY (`FROM_PARTY_ID`,`PARTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_MESSAGE_LOG` (
  `SEQNO` varchar(8) NOT NULL,
  `SUBSEQNO` varchar(5) NOT NULL,
  `UUID` varchar(40) DEFAULT NULL,
  `MESSAGE_TYPE` varchar(10) DEFAULT NULL,
  `CATEGORY_TYPE` varchar(5) DEFAULT NULL,
  `PROCESS_TYPE` varchar(10) DEFAULT NULL,
  `FROM_PARTY_ID` varchar(10) DEFAULT NULL,
  `TO_PARTY_ID` varchar(10) DEFAULT NULL,
  `MESSAGE_DTS` varchar(17) DEFAULT NULL,
  `CHARACTER_COUNT` varchar(10) DEFAULT NULL,
  `STATUS` varchar(5) DEFAULT NULL,
  `IN_OUT_BOUND` varchar(1) DEFAULT NULL,
  `FROM_ROUTING_ID` varchar(39) DEFAULT NULL,
  `TO_ROUTING_ID` varchar(39) DEFAULT NULL,
  `INVOICE_IDENTIFIER` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SEQNO`,`SUBSEQNO`) USING BTREE,
  KEY `TURNKEY_MESSAGE_LOG_INDEX1` (`MESSAGE_DTS`),
  KEY `TURNKEY_MESSAGE_LOG_INDEX2` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_MESSAGE_LOG_DETAIL` (
  `SEQNO` varchar(8) NOT NULL,
  `SUBSEQNO` varchar(5) NOT NULL,
  `PROCESS_DTS` varchar(17) DEFAULT NULL,
  `TASK` varchar(30) NOT NULL,
  `STATUS` varchar(5) DEFAULT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  `UUID` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`SEQNO`,`SUBSEQNO`,`TASK`),
  KEY `TURNKEY_MESSAGE_LOG_DETAIL_INDEX1` (`FILENAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_SEQUENCE` (
  `SEQUENCE` varchar(8) NOT NULL,
  PRIMARY KEY (`SEQUENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_SYSEVENT_LOG` (
  `EVENTDTS` varchar(17) NOT NULL,
  `PARTY_ID` varchar(10) DEFAULT NULL,
  `SEQNO` varchar(8) DEFAULT NULL,
  `SUBSEQNO` varchar(5) DEFAULT NULL,
  `ERRORCODE` varchar(4) DEFAULT NULL,
  `UUID` varchar(40) DEFAULT NULL,
  `INFORMATION1` varchar(100) DEFAULT NULL,
  `INFORMATION2` varchar(100) DEFAULT NULL,
  `INFORMATION3` varchar(100) DEFAULT NULL,
  `MESSAGE1` varchar(100) DEFAULT NULL,
  `MESSAGE2` varchar(100) DEFAULT NULL,
  `MESSAGE3` varchar(100) DEFAULT NULL,
  `MESSAGE4` varchar(100) DEFAULT NULL,
  `MESSAGE5` varchar(100) DEFAULT NULL,
  `MESSAGE6` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EVENTDTS`),
  KEY `TURNKEY_SYSEVENT_LOG_INDEX1` (`SEQNO`,`SUBSEQNO`),
  KEY `TURNKEY_SYSEVENT_LOG_INDEX2` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_TRANSPORT_CONFIG` (
  `TRANSPORT_ID` varchar(10) NOT NULL,
  `TRANSPORT_PASSWORD` varchar(60) NOT NULL,
  PRIMARY KEY (`TRANSPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TURNKEY_USER_PROFILE` (
  `USER_ID` varchar(10) NOT NULL,
  `USER_PASSWORD` varchar(100) DEFAULT NULL,
  `USER_ROLE` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;